source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '13.0'

target 'DomestikaTrailers' do
  # Pods for DomestikaTrailers

	## SnapKit: a wrapper on top of autolayout
	pod 'SnapKit'
  
  ## HUD meant to display the progress of an ongoing task on iOS
  pod 'SVProgressHUD'

  target 'DomestikaTrailersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DomestikaTrailersUITests' do
    # Pods for testing
  end
end
